# Generated by Django 4.2.6 on 2023-10-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_recordlabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='record_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='albums.recordlabel'),
        ),
    ]
